version: '3.8'
services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  server:
    image: server
    container_name: server-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379  # Use the service name "redis"
      - MONGODB_URI=mongodb://mongo:27017/code-editor
    depends_on:
      - redis
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=code-editor
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network: